### ISSUE TITLE
Missing functions inside model class

### ISSUE THREAD

**Issue by lorisgir** [qiumiao30/SLMR#1]
Hi, thanks for you work!
I wanted to train the dataset but I noticed that these functions are not implemented:

- conv5x5
- deconv5x5
- deconv3x3
- deconv1x1

but they are been called in file `se_in_gru_zhiqian.py` line 26-30. 
Could you add them?

**Comment by qiumiao30** [comment]
line 20-->`class Res2NetBottleneck()` should be annotated out.

**Comment by lorisgir** [comment]
Thanks!
