### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './datasets/data/smap_train_md.csv'

### ISSUE THREAD

**Issue by 943fansi** [qiumiao30/SLMR#3]
Thanks for your excellent work. I met an error, could you please help me?

**Comment by qiumiao30** [comment]
https://github.com/qiumiao30/SLMR/tree/master/datasets/data

**Comment by 943fansi** [comment]
> https://github.com/qiumiao30/SLMR/tree/master/datasets/data
Your reply was very quick, thank you.

**Comment by 943fansi** [comment]
@qiumiao30 In `preprocess.py` line 12, `temp = np.genfromtxt(md['num_values'],`  `md` is not defined before.

**Comment by qiumiao30** [comment]
python preprocess.py --dataset $dataset_name$
