### ISSUE TITLE
Can I use the fault data set of the wind turbine for anomaly detection? What parts do I need to modify？

### ISSUE THREAD

**Issue by 943fansi** [qiumiao30/SLMR#4]
My data is a excel file, which includes multi sensors' values and known label is the failure timestamp at some time. Does `SLMR` method is suitable for this problem? Looking forward to your reply, Dr. Miao.

**Comment by qiumiao30** [comment]
那是必须滴

**Comment by 943fansi** [comment]
> 那是必须滴

好的，[1]周小晖,王意洁,徐鸿祚,刘铭宇.基于融合学习的无监督多维时间序列异常检测[J/OL].计算机研究与发展:1-14.这篇文章的作者您认识吗？

**Comment by 943fansi** [comment]
@qiumiao30 训练集中可以包含异常数据吗，还是仅使用正常数据做训练？

**Comment by qiumiao30** [comment]
全部正常

在 943fansi ***@***.***>，2022年12月3日 上午9:41写道：

@qiumiao30<https://github.com/qiumiao30> 训练集中可以包含异常数据吗，还是仅使用正常数据做训练？

**Comment by 943fansi** [comment]
@qiumiao30 感谢您的解答，请问您知道有可以包含异常数据进行训练的模型吗？
