### ISSUE TITLE
Results and parameters of swat data

### ISSUE THREAD

**Issue by Hannnner** [qiumiao30/SLMR#6]
Hello, thanks for your excellent work!
I used SWAT for training, and here are my results, which are quite different from those in the paper.
**Results using best f1 score search:
 {'f1': 0.2649609229935174, 'precision': 0.15363522887271114, 'recall': 0.9621940277618143, 'TP': 52556, 'TN': 105761, 'FP': 289527, 'FN': 2065, 'threshold': 0.4999999999999782, 'latency': 34.9998870971384}**

I think there may be a problem with my parameter. I run the following swat parameters:
    **# -- Data params ---
    parser.add_argument("--dataset", type=str.upper, default="SWAT")
    parser.add_argument("--group", type=str, default="1-1", help="Required for SMD dataset. <group_index>-<index>")
    parser.add_argument("--lookback", type=int, default=10, help="Windows size")
    parser.add_argument("--normalize", type=str2bool, default=True)
    parser.add_argument("--spec_res", type=str2bool, default=False)
    parser.add_argument("--mask_ratio", type=float, default=0.1)**
    **# -- Model params ---
    # 1D conv layer
    parser.add_argument("--kernel_size", type=int, default=7)
    # GAT layers
    parser.add_argument("--use_gatv2", type=str2bool, default=False)
    parser.add_argument("--feat_gat_embed_dim", type=int, default=None)
    parser.add_argument("--time_gat_embed_dim", type=int, default=None)
    # GRU layer
    parser.add_argument("--gru_n_layers", type=int, default=1)
    parser.add_argument("--gru_hid_dim", type=int, default=150)
    # Forecasting Model
    parser.add_argument("--fc_n_layers", type=int, default=1)
    parser.add_argument("--fc_hid_dim", type=int, default=150)
    # Reconstruction Model
    parser.add_argument("--recon_n_layers", type=int, default=1)
    parser.add_argument("--recon_hid_dim", type=int, default=150)
    # Other
    parser.add_argument("--alpha", type=float, default=0.2)**
    **# --- Train params ---
    parser.add_argument("--epochs", type=int, default=10)
    parser.add_argument("--val_split", type=float, default=0.1)
    parser.add_argument("--bs", type=int, default=256)
    parser.add_argument("--init_lr", type=float, default=1e-3)
    parser.add_argument("--shuffle_dataset", type=str2bool, default=True)
    parser.add_argument("--dropout", type=float, default=0.3)
    parser.add_argument("--use_cuda", type=str2bool, default=True)
    parser.add_argument("--print_every", type=int, default=1)
    parser.add_argument("--log_tensorboard", type=str2bool, default=True)**
    **# --- Predictor params ---
    parser.add_argument("--scale_scores", type=str2bool, default=False)
    parser.add_argument("--use_mov_av", type=str2bool, default=False)
    parser.add_argument("--gamma", type=float, default=1)
    parser.add_argument("--level", type=float, default=None)
    parser.add_argument("--q", type=float, default=None)
    parser.add_argument("--dynamic_pot", type=str2bool, default=False)
    parser.add_argument("--adjust_score", type=str2bool, default=True)**
    **# --- Other ---
    parser.add_argument("--comment", type=str, default="")**

Can you provide the parameters used to train the SWAT in the paper?
Thank you very much!

**Comment by qiumiao30** [comment]
I think there is a problem with your data processing, although different parameters will have a different impact on performance, but not so much.

**Comment by Hannnner** [comment]
The shape of SWaT_Dataset_Normal_v0.csv is [496800,53] and the shape of SWaT_Dataset_Attack_v0.csv is [449919,53]. I think the original data is no problem.
I ran the preprocess.py in the code to generate the pkl file and rechecked the data and found nothing wrong. 
If it is convenient for you, could you please send me the pkl file after swat data processing to my email hanxt0830@163.com? 
Thank you very much, it will be of great help to me!

**Comment by WSake** [comment]
It's a very good paper. When I reproduced it, the accuracy of the SWaT dataset was also relatively low, or even very poor. Could you please send me the pkl file after swat data processing to my email (1813214195@qq.com) .Looking forward to your reply. Thank you very much
